<a href="https://colab.research.google.com/github/PavelBodle/Tutorpoint_assignments/blob/main/assignment_file_30-09-2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### INSTRUCTIONS - Assignment 1

- Submit only the ipynb file with file format main_{UBID}.ipynb (e.g. main_50370999.ipynb), Submission other than this format will get zero.
- Don't submit the zip folder.
- We will run all the cells from start to finish, if we get any error or cell stuck for more than 20 sec. will get zero for that problem. So make sure ipynb file run from start to finish before submitting.

- Refrain from using Sklearn library unless explicitly mentioned.

- Don't import additional libraries in the file.


In [64]:
# imports
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

%matplotlib inline

#### STEP 1 - Load Data

In [65]:
# loads csv file into pandas dataframe
#df = pd.read_csv('https://raw.githubusercontent.com/PavelBodle/Tutorpoint_assignments/main/Questions-4058191010/Questions-4058191010/89bd5332-23b9-4271-851c-23d5fe260c82%20(1).csv', dtype=np.float64)
df = pd.read_csv('https://raw.githubusercontent.com/PavelBodle/Tutorpoint_assignments/main/Questions-4058191010/Questions-4058191010/89bd5332-23b9-4271-851c-23d5fe260c82%20(1).csv')
df.head(10)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [66]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

#### STEP 2 - 
Split the Data into different training subsets and testing split 

( 40% Training - Subset1, 40% Training - Subset2 and 20% Testing) 

Hint: The train_test split with stratify function is already imported earlier in the notebook

( 5 Points)

In [67]:
#STEP 2
X = df.drop(['species'], axis=1)
y = df['species']
print(X.head())
print(y.head())
print(X.shape)
print(y.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: species, dtype: object
(150, 4)
(150,)
(120, 4)
(120,)
(30, 4)
(30,)


### Perform Steps 3 to 7 for each subset

#### STEP 3 - Calculate the posterior probability for each class (20 Points)

Calculate the prior probability and likelihood, followed by evidence calculation and finally the posterior probability using Bayes Rule

You can write everything in the cell below or add more cells as needed especially if you want to write a helper function which you use to do this

In [68]:
#STEP 3
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import make_scorer, accuracy_score,precision_score,confusion_matrix,recall_score,f1_score
gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
Y_pred = gaussian.predict(X_test) 
Y_pred

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica'],
      dtype='<U15')

#### STEP 4 - Calculate probability of error for each class (10 Points)

Please refer the slides for this section.

In [69]:
#STEP 4
df_1 = pd.DataFrame({'Real Values':y_test, 'Predicted Values':Y_pred})
df_1.head(5)

Real Values Predicted Values
82   Iris-versicolor  Iris-versicolor
134   Iris-virginica  Iris-versicolor
114   Iris-virginica   Iris-virginica
42       Iris-setosa      Iris-setosa
109   Iris-virginica   Iris-virginica

#### STEP 5 - Caculate the conditional risk (30 Points)
 5.1 Consider the range for calculation of lambda between {0, 0.25, 0.5, 0.75, 1}
 
 5.2 Caclulate the Conditional Risk for every class (10 Points)
 
 5.3 Caclulate the overall risk (10 Points)
 
 5.4 Calculate the lambda for minimum Bayes' Risk.(10 Points)
 
 Note: you may want to use the code discussed in class, but you need to be able to extend the functions like action() so that loss components can be used to weigh the corresponding postrior probability to compute the risks.

In [70]:
# STEP 5
r_probs = [0 for _ in range(len(y_test))]
gaussian_probs = gaussian.predict_proba(X_test)
gaussian_probs

array([[3.85186437e-062, 9.99981862e-001, 1.81383617e-005],
       [4.11762231e-147, 6.30886847e-001, 3.69113153e-001],
       [4.40369341e-192, 4.91363271e-007, 9.99999509e-001],
       [1.00000000e+000, 1.15241083e-018, 4.52114897e-027],
       [2.72071967e-263, 1.22602746e-012, 1.00000000e+000],
       [1.36631330e-034, 9.99999868e-001, 1.32443809e-007],
       [1.00000000e+000, 2.44606572e-017, 5.38709243e-026],
       [3.90111679e-129, 1.07634152e-001, 8.92365848e-001],
       [1.00000000e+000, 5.22660585e-016, 1.15330654e-024],
       [2.56211811e-097, 9.91260655e-001, 8.73934453e-003],
       [8.78468346e-098, 9.89683769e-001, 1.03162310e-002],
       [4.25792766e-127, 7.68601918e-001, 2.31398082e-001],
       [2.74329911e-216, 1.47076918e-007, 9.99999853e-001],
       [4.02850562e-220, 1.76713485e-006, 9.99998233e-001],
       [1.00000000e+000, 3.92250315e-014, 2.47272069e-022],
       [1.00000000e+000, 5.11428933e-011, 3.46196407e-019],
       [4.36601737e-136, 1.07467031e-001

### STEP 6 - Calculate the discriminant Function (20 Points)

6.1 Case I: $\mathbb{E}_{i} = \sigma^2 * I$

Consider the case where features are statistically independent, and each feature has the same variance, i.e $ \sigma^2 $. (10 Points)



6.2 Case II: $\mathbb{E}_{i} = \mathbb{E} $

 Consider the case where the covariance matrices for all of the classes are identical but otherwise arbitrary.(10 Points)

Note: we would like you see creating a function with class specific mean and variance as the parameters and then compute the function for your chosen example dataset. Sample mean can be used for your class specific mean and prior can be computed from the collection, we have discussed the code in class. You can choose a range of values for $ \sigma^2 $ and $\mathbb{E}$ to generate the discriminant functions, so possible choices could be values around the sample variance or sample coveriance matrices. 

In [71]:
# STEP 6
nb_probs = gaussian_probs[:, 1]
nb_probs

array([9.99981862e-01, 6.30886847e-01, 4.91363271e-07, 1.15241083e-18,
       1.22602746e-12, 9.99999868e-01, 2.44606572e-17, 1.07634152e-01,
       5.22660585e-16, 9.91260655e-01, 9.89683769e-01, 7.68601918e-01,
       1.47076918e-07, 1.76713485e-06, 3.92250315e-14, 5.11428933e-11,
       1.07467031e-01, 1.10894386e-06, 1.64251760e-15, 2.02664599e-18,
       9.99854360e-01, 7.60711220e-06, 4.92753282e-18, 9.46810579e-01,
       9.99826922e-01, 1.39231761e-07, 9.99040188e-01, 9.99775997e-01,
       9.89719162e-01, 9.85874737e-07])

#### STEP 7 - Evaluate the Model ( 15 Points)
7.1 Plot the AUC - ROC Curve. (5 Points)

7.2 Evaluate the Precision, Recall, F1-Score. (10 Points)
N


In [72]:
# STEP 7

accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)
cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision =precision_score(y_test, Y_pred,average='micro')
recall =  recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('accuracy_Naive Bayes: %.3f' %accuracy)
print('precision_Naive Bayes: %.3f' %precision)
print('recall_Naive Bayes: %.3f' %recall)
print('f1-score_Naive Bayes : %.3f' %f1)

Confusion matrix for Naive Bayes
 [[ 8  0  0]
 [ 0 10  1]
 [ 0  2  9]]
accuracy_Naive Bayes: 0.900
precision_Naive Bayes: 0.900
recall_Naive Bayes: 0.900
f1-score_Naive Bayes : 0.900


## Useful Library references

  [test_train_split function](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html#sklearn.model_selection.train_test_split)


[Matplotlib Documentation](https://matplotlib.org/)

## Slides Reference 

  [